FROM python:3.9

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt
COPY publish_sns.py /usr/bin/publish_sns.py

#CMD ["python", "/usr/bin/publish_sns.py", "/data/job_data.json", "--aws_auth_method", "keys"]